### ISSUE TITLE
Support for version 4.1.1?

### ISSUE THREAD

**Issue by drtomasso** [calmh/unifi-api#21]
I've just upgraded to UniFi v4.1.1 and the API stopped working. I'm using the API to check the controller for disconnected AP. It worked perfectly with v3.x.

This is the error message I get when running the script:
```
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_unifi_ap.py", line 74, in <module>
    main(sys.argv[1:])
  File "/usr/lib/nagios/plugins/check_unifi_ap.py", line 43, in main
    for us in c.get_clients():
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 129, in get_clients
    return self._read(self.api_url + 'stat/sta')
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 75, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

And my script:
```python
#!/usr/bin/python2.7

import sys, getopt

def main(argv):
   ctrlServ = ''
   ctrlUser = ''
   ctrlPass = ''
   ctrlVers = ''
   ctrlSite = ''
   ctrlExcp = ''

   try:
      opts, args = getopt.getopt(argv,"hH:u:p:v:s:x:")
   except getopt.GetoptError:
      print 'check_unifi_ap.py -H <servername or IP> -u <user> -p <password> -v <version> -s <site name> -x <ignore AP list>'
      sys.exit(3)
   for opt, arg in opts:
      if opt == '-h':
         print 'check_unifi_ap.py -H <servername or IP> -u <user> -p <password> -v <version> -s <site name> -x <ignore AP list>'
         sys.exit(3)
      elif opt in ("-H"):
         ctrlServ = arg
      elif opt in ("-u"):
         ctrlUser = arg
      elif opt in ("-p"):
         ctrlPass = arg
      elif opt in ("-v"):
         ctrlVers = arg
      elif opt in ("-s"):
         ctrlSite = arg
      elif opt in ("-x"):
         ctrlExcp = arg.split(",")

   uAP = True
   eStr = 'Offline:'
   nUsers = 0
   nGuests = 0

   from unifi.controller import Controller
   c = Controller(ctrlServ, ctrlUser, ctrlPass, ctrlVers, ctrlSite)

   for us in c.get_clients():
     if us['is_guest'] == True:
        nGuests += 1
     else:
        nUsers += 1

   for ap in c.get_aps():
     if ap['name'] in ctrlExcp:
        continue
     try:
        #print '%s is up: %s' % (ap['name'], ap['uplink']['up'])
        if ap['uplink']['up'] == False:
           uAP = False
           eStr += ' ' + ap['name']
     except (KeyError, IndexError):
         #print '%s is disconnected' % (ap['name'])
        uAP = False
        eStr += ' ' + ap['name']

   if uAP == True:
     str = 'OK - All AP is online'
     str = str + '. Connected Users: %s. Connected Guests: %s' % (nUsers, nGuests)
     print str
     sys.exit(0)
   else:
     str = 'CRITICAL - %s' % (eStr)
     str = str + '. Connected Users: %s. Connected Guests: %s' % (nUsers, nGuests)
     print str
     sys.exit(2)

if __name__ == "__main__":
   main(sys.argv[1:])
```

**Comment by andrewwippler** [comment]
merge request #25 resolves this issue.
