### ISSUE TITLE
HTTP Error 401

### ISSUE THREAD

**Issue by mholttech** [calmh/unifi-api#31]
I'm getting this error:
````
root@unifi:~# unifi-ls-clients -c localhost -u admin -p <pass> -v v3 -s default
Traceback (most recent call last):
  File "/usr/local/bin/unifi-ls-clients", line 18, in <module>
    aps = c.get_aps()
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 198, in get_aps
    return self._read(self.api_url + 'stat/device', params)
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 120, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
````

any idea what's wrong?

**Comment by calmh** [comment]
Wrong password?

**Comment by mholtrlc** [comment]
nope, it's the same exact login I use to log into the controller's web interface

**Comment by Dwarf8** [comment]
I got the same error.

Traceback (most recent call last):
  File "/usr/local/bin/unifi-save-statistics", line 19, in <module>
    statistics = c.get_statistics_last_24h()
  File "/Library/Python/2.7/site-packages/unifi/controller.py", line 120, in get_statistics_last_24h
    return self.get_statistics_24h(time.time())
  File "/Library/Python/2.7/site-packages/unifi/controller.py", line 127, in get_statistics_24h
    return self._read(self.api_url + 'stat/report/hourly.system', params)
  File "/Library/Python/2.7/site-packages/unifi/controller.py", line 78, in _read
    res = self.opener.open(url, params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 513, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 438, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 372, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 521, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by thomasbergmann** [comment]
same here:

/usr/local/bin/unifi-low-snr-reconnect -c localhost -u XXX -p XXX -v v3 -s default --minsnr 20
Traceback (most recent call last):
  File "/usr/local/bin/unifi-low-snr-reconnect", line 26, in <module>
    all_aps = c.get_aps()
  File "/usr/local/lib/python3.2/dist-packages/unifi/controller.py", line 198, in get_aps
    return self._read(self.api_url + 'stat/device', params)
  File "/usr/local/lib/python3.2/dist-packages/unifi/controller.py", line 116, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python3.2/urllib/request.py", line 376, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 488, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 414, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 496, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

user, password and site are correct

**Comment by thomasbergmann** [comment]
didn´t realized a new api... changed to v4 and it works (at least I get another error)

**Comment by marcogaio** [comment]
I'm getting mee too that error; controller version 4.7.6-6357 (debian packages).
```
invernomuto:~# unifi-ls-clients -c localhost -v v4 -u root -p OMISSIS -s default
Traceback (most recent call last):
  File "/usr/local/bin/unifi-ls-clients", line 18, in <module>
    aps = c.get_aps()
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 205, in get_aps
    return self._read(self.api_url + 'stat/device', params)
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 120, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python2.7/urllib2.py", line 407, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 445, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```
Password is correct, seems to me an api trouble...

**Comment by marcogaio** [comment]
Ok, this simple patch solves the connection trouble: https://github.com/jgarland79/unifi-api/commit/aadfa4dcb28179b8214d00f79e458ea521cb68e8

Why no one commit it?

**Comment by celsowebber** [comment]
Just tried the patch mentioned by marcogaio and it worked against controller version 4.8.12!

**Comment by dilruacs** [comment]
controller version 4.8.12-7387, used latest version from git (now including jgarland79@aadfa4d as far as I can see), no luck

**Comment by dilruacs** [comment]
See #36 [https://github.com/calmh/unifi-api/issues/36#issuecomment-185616071](url)

**Comment by calmh** [comment]
v4 support merged
