### ISSUE TITLE
unifi-save-statistics error

### ISSUE THREAD

**Issue by rusfat** [calmh/unifi-api#41]
Hello!

When i execute this command 

unifi-save-statistics -c localhost -u login -p password -v v4

i get this output:

Traceback (most recent call last):
  File "/usr/local/bin/unifi-save-statistics", line 20, in <module>
    statistics = c.get_statistics_last_24h()
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 178, in get_statistics_last_24h
    return self.get_statistics_24h(time())
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 186, in get_statistics_24h
    return self._read(self.api_url + 'stat/report/hourly.system', params)
  File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 120, in _read
    res = self.opener.open(url, params)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

Can u please help me with this issue?

**Comment by calmh** [comment]
I think you omitted the actual error. But in any case, this is mostly an API with some examples; if the example doesn't work you may need to do some debugging. :/ Sorry
