### ISSUE TITLE
json syntax error when attempting to reboot ap by name or MAC

### ISSUE THREAD

**Issue by KevinComputech** [calmh/unifi-api#49]
Hey guys,

My Python is a little rusty, but I'm working on a script to manage our APs and part of that is rebooting them. I can't seem to get the restart_ap or restart_ap_name to work correctly. I'm just trying to get the command with a hardcoded name or mac, but I get the same syntax error. 

`>>> c.restart_ap_name('BreakRoom')`
`Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    c.restart_ap_name('BreakRoom')
  File "C:\Program Files (x86)\Python\lib\site-packages\unifi\controller.py", line 295, in restart_ap_name
    self.restart_ap(ap['mac'])
  File "C:\Program Files (x86)\Python\lib\site-packages\unifi\controller.py", line 281, in restart_ap
    self._mac_cmd(mac, 'restart', 'devmgr')
  File "C:\Program Files (x86)\Python\lib\site-packages\unifi\controller.py", line 238, in _mac_cmd
    self._run_command(command, params, mgr)
  File "C:\Program Files (x86)\Python\lib\site-packages\unifi\controller.py", line 233, in _run_command
    return self._read(self.api_url + 'cmd/' + mgr, urllib.parse.urlencode({'json': json.dumps(params)}))
  File "C:\Program Files (x86)\Python\lib\site-packages\unifi\controller.py", line 112, in _read
    params = ast.literal_eval(params)
  File "C:\Program Files (x86)\Python\lib\ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Program Files (x86)\Python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    json=%7B%22cmd%22%3A+%22restart%22%2C+%22mac%22%3A+%2224%3Aa4%3A3c%3A6a%3A84%3A1e%22%7D
        ^
SyntaxError: invalid syntax`

I'm probably doing something obvious but any help would be appreciated.

**Comment by KevinComputech** [comment]
So after a good bit of digging I figured out the issue. It looks like for some reason the line in controller.py:
`def _read(self, url, params=None):
        if PYTHON_VERSION == 3:
            if params is not None:
                **params = ast.literal_eval(params)**
                #print (params)
                params = urllib.parse.urlencode(params)`
Is the issue. The string that it is passed is something that doesn't work for whatever reason, I'm not sure of the details behind it being an percent-encoded string, something like:

`json=%7B%22cmd%22%3A+%22restart%22%2C+%22mac%22%3A+%2224%3Aa4%3A3c%3A6a%3A84%3A1e%22%7D`

I ended up commenting out the literal_eval as well as the urlencode after. As that was already done in a previous function and only exists to re-encode after the eval.

`    def _read(self, url, params=None):
        if PYTHON_VERSION == 3:
            if params is not None:
                #params = ast.literal_eval(params)
                #print (params)
                #params = urllib.parse.urlencode(params)`

After that the reboot_ap() worked flawlessly.
